# Generated by Django 5.2.17 on 2026-08-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50)),
                ('material_type', models.CharField(choices=[('PET', 'PET Plastic'), ('aluminum', 'Aluminum'), ('paper', 'Paper'), ('glass', 'Glass')], max_length=20)),
                ('item_count', models.PositiveIntegerField()),
                ('event_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
